name = "SelfContainedScripts"
uuid = "93902f1d-9a2b-41c9-a18c-38c62c54fa29"
authors = ["Christopher Doris <github.com/cjdoris>"]
version = "0.1.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
Pkg = "1.11"
TOML = "1.0"
Test = "1.0"
TestItemRunner = "1.1"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner"]
